[auth]
# Disable email confirmation
enable_confirmations = false
enable_signup = true

[functions.nano-banana]
enabled = true
verify_jwt = false
import_map = "./functions/nano-banana/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/nano-banana/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/nano-banana/*.html" ]
